include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - avoid_print
    - avoid_unnecessary_containers
    - prefer_single_quotes
    - use_key_in_widget_constructors

analyzer:
  errors:
    invalid_annotation_target: ignore
